bug:
  issue:
    comment: Thanks for reporting this bug! We'll triage it soon.
    label: triage
feature:
  issue:
    comment: Thanks for the feature request! We'll review it.
    label: enhancement
overview:
  issue:
    comment: Thanks for the project documentation.
    label: documentation
