bug:
  comment: Thanks for reporting this bug! We'll triage it soon.
  add_label: triage
feature:
  comment: Thanks for the feature request! We'll review it.
  add_label: enhancement
overview:
  comment: Thanks for the project documentation.
  add_label: documentation
