name: 'Label Actions'
on: 
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]
permissions: 
  contents: read
  issues: write
  pull-requests: write
  discussions: write
jobs:
  testingLabelAction:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - uses: dessant/label-actions@v4
      
