name: 'Label Actions'
on: 
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]
permissions: 
  contents: read
  issues: read
  pull-requests: write
  discussions: write
jobs:
  testingLabelAction:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v4
      
